### PR TITLE
Upgrade to Angular v5

### PR DESCRIPTION
**Pull request by pedroraft**
import 'rxjs/add/operator/map';

problem solved!

### CODE REVIEW

**Comment by pedroraft** [comment]
Sorry about the linting hehe

**Comment by pedroraft** [comment]
@DavideViolante i can confirm bug #105, maybe we should try to fix this in v5.

**Comment by DavideViolante** [comment]
Ignore #105 for now, I've another bug and I'm not sure if I've introduced it just now, but I don't think so. When you type wrong username or password in Login page, you anyway get redirected to homepage without getting the Toast error message.

**Comment by pedroraft** [comment]
nice catch, i knew there was something fishy about that pattern i did.

**Comment by pedroraft** [comment]
@DavideViolante removing the return when updating or deleting an item will cause error when http client tries to deserialize the body .

**Comment by DavideViolante** [comment]
Hmm, seems like a bug from Angular itself: https://github.com/angular/angular/issues/18680

**Pull request merged**
