### PR TITLE
secure api /w auth0 angular-jwt + express-jwt (wip)

### PR DESCRIPTION
**Pull request by dougal83**
Updated effort to secure the API.  Please note that a major component is still considered a beta namely: "auth0/angular-jwt": "^1.0.0-beta.9". UPDATE: auth0/angular-jwt maintainer intends to release stable version in the near future.

**Notes:-**
Deployment:

- client/app/routing.module.ts > whitelistedDomains will need to be set accordingly.  This prevents our token being sent to unapproved domains.

Attention required(aka. can you do it Davide? ;-) ):

- .spec.ts need an update due to replacement of loggedIn variable.

**TODO:**

- evolve role based security toward oauth2 scope sauce? (i.e. [api scope example](https://api.slack.com/docs/oauth-scopes))
- JWT refresh mechanism with regard to revoked token issues?
- Testing!  Need others to look for holes in the implementation.

### CODE REVIEW

**Comment by timelf123** [comment]
Loved your third-party-login branch @dougal83 any plans on finishing it? looks to me like the only thing left is adding an `auth.authenticate` method to the frontend service and set up the server side strategies?

**Comment by timelf123** [comment]
@dougal83 let me know if I can help finish this up

**Comment by dougal83** [comment]
Feel free to make use of any of the code to submit a pull request to Davide
for it. I don't have time to do it ATM.

**Comment by timelf123** [comment]
After finishing up a production app with these changes among others, I'll port the resulting work into a PR. Will be borrowing code/techniques from https://github.com/domfarolino/angular2-login-seed

**Pull request closed without merging**
