### PR TITLE
Code Refactor in Angular2

### PR DESCRIPTION
**Pull request by midhunadarvin**
- Create a separate shared module to contain all common modules, components, and services.
- Issue no. #36  Fix

### CODE REVIEW

**Comment by midhunadarvin** [comment]
Intergrated [ng2-resource-rest](https://github.com/troyanskiy/ng2-resource-rest) REST Client with Angular2.

**Comment by DavideViolante** [comment]
Wait wait, you are changing too much the project and the main goal is to keep it as simple as possible. Adding new libraries won't help new users to get started with this project.
Also a recommendation: keep the changes and the PRs atomic (for any project you contribute). For example this PR contains 3 main changes:
- fix of #36 (that I may approve)
- create shared module (that I maybe approve)
- add ng2-resource-test (that I don't like)

**Comment by midhunadarvin** [comment]
Okay, So should i revert back the master branch of my fork for the PR?

**Comment by DavideViolante** [comment]
You should work on branches on your fork too. Open different PRs for the different tasks.
I think you should create another branch starting from my master, then git cherry-pick the commits you want to add to that branch, for example 	684670c.

**Pull request closed without merging**
